name: ShowServerAddr
version: '1.1'
main: com.github.bayingwolf149.showserveraddr.ShowServerAddr
website: http://dev.bukkit.org/server-mods/showserveraddr/
author: BayingWolf149
commands:
  ssa:
    description: Used to view the servers web address.
    usage: /ssa <arg> [address]
permissions:
  showserveraddr.resetadd:
    description: Allows users access to the /ssd resetadd command.
    default: op
  showserveraddr.setadd:
    description: Allows users access to the /ssd setadd command.
    default: op
  showserveraddr.viewadd:
    description: Allows users access to the /ssd command.